-d C:\Users\koray\Documents\gowin\ALU\impl\gwsynthesis\ALU.vg
-p GW2A-18-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\koray\Documents\gowin\ALU\src\top.cst
-cfg C:\Users\koray\Documents\gowin\ALU\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
